"""
Django settings for worktracker project.
Generated by 'django-admin startproject' using Django 5.2.3.
"""
import os # <- Добавлено для работы с переменными окружения
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- 1. КРИТИЧЕСКИ ВАЖНО: Настройки безопасности ---
# Никогда не храните секретные данные в коде. Используйте переменные окружения.
# В разработке можно использовать os.getenv с значением по умолчанию.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-&!^=w2d$rt^#$k%8v*piko2cwrp7=o0ctzfj-y%6%9t#$r_)p$')

# DEBUG должен быть False в продакшене.
# Удобно управлять им через переменную окружения (любое значение кроме 'False' будет True).
DEBUG = os.getenv('DJANGO_DEBUG', 'True') != 'False'

# В режиме DEBUG = True можно разрешить все хосты, но для продакшена это должно быть строго определено.
ALLOWED_HOSTS = []
if not DEBUG:
    # Замените 'yourdomain.com' на ваш реальный домен
    ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'yourdomain.com,www.yourdomain.com').split(',')
else:
    ALLOWED_HOSTS = ['*'] # Для удобства в разработке


# --- 2. Улучшение структуры INSTALLED_APPS ---
# Группировка приложений улучшает читаемость
INSTALLED_APPS = [
    # Встроенные приложения Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Сторонние приложения (если будут)
    # 'rest_framework',

    # Ваши локальные приложения
    'employees.apps.EmployeesConfig', # <- Улучшение: Явное указание конфигурации приложения
]

# --- 3. Улучшение порядка MIDDLEWARE ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # LocaleMiddleware должен идти после SessionMiddleware и до CommonMiddleware
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'worktracker.urls'

# --- 4. Улучшение конфигурации шаблонов ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Добавляем общую папку для шаблонов на уровне проекта
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'worktracker.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# Примечание: для продакшена настоятельно рекомендуется использовать PostgreSQL или MySQL.

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- 5. Исправление формата LANGUAGE_CODE ---
LANGUAGE_CODE = 'ru-RU'  # <- Исправление: Стандартный формат 'язык-СТРАНА'
TIME_ZONE = 'Europe/Moscow' # <- Улучшение: Укажите конкретный часовой пояс вместо UTC
USE_I18N = True
USE_TZ = True

# --- 6. Улучшение конфигурации статических файлов ---
STATIC_URL = 'static/'
# Папка, куда `collectstatic` будет собирать все статические файлы для продакшена.
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Папки, где Django будет искать статические файлы в дополнение к папкам приложений.
STATICFILES_DIRS = [BASE_DIR / "static"]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- 7. Автоматические настройки безопасности в зависимости от DEBUG ---
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 год
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # SECURE_BROWSER_XSS_FILTER = True # Устарело и не нужно в современных браузерах
    # X_FRAME_OPTIONS = 'DENY' # Уже включено по умолчанию через XFrameOptionsMiddleware